---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2024-11-19T09:59:31.680722294Z"
  name: instavote
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/LFS269-Ruwbdy/instavote.git
