---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: vote
  namespace: flux-system
spec:
  exclusionList:
  - ^.*\.sig$
  image: ruwbdy/vote
  interval: 1m0s
  provider: generic
